version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /node_modules
    environment:
      - NODE_ENV=production
    working_dir: /ai-chatbot-frontend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
