services:
  web:
    build: ./ai-chatbot-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /node_modules
    environment:
      - NODE_ENV=production
    working_dir: /ai-chatbot-frontend

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
      
  ai_service:
    image: tensorflow/tensorflow:latest-gpu
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    command: tail -f /dev/null
volumes:
  mongodb_data_container:
