version: "3.8"

services:
  web:
    build: ./ai-chatbot-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./ai-chatbot-frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: node server.js

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  ai:
    build: ./AI-backend
    ports:
      - "8000:8000"
    volumes:
      - ./AI-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data_container:
